### PR TITLE
Report an invalid state error when core.rtcdatachannel.send will fail.

### PR DESCRIPTION
**Pull request by bemasc**

### CODE REVIEW

**Comment by bemasc** [comment]
@trevj @iislucas PTAL

**Comment by willscott** [comment]
FYI: this looks good. we were trying to getyhe ci tests re stabilized
yesterday, which is why it isn't merged yet

**Comment by bemasc** [comment]
OK, thanks.  There's no huge rush on this (although it would be useful to get it in when possible).

**Comment by trevj** [comment]
Essentially, you're enabling functionality that's currently impossible due to the asynchronous interface. Cool. However, I have a few concerns:
 * You're *forcing* users to use this. I think it would be better to create a new method, e.g. `checkStateAndSend`.
 * What *other* helper functions you would add -- and when does the motivation become high enough to special-case these joint operations? It's not clear to me that this particular one is so important. For example, close events should fire right after the connection closes.
 * Will this interface still be a thin wrapper over the object?

The second is my biggest concern. I thought the underlying problem was that JavaScript's lack of an exception hierarchy makes it hard to distinguish between different types of errors, e.g. fatal errors like "ran out of memory" and recoverable errors like "connection closed". I would encourage us to research that issue a little more.

**Comment by bemasc** [comment]
> Will this interface still be a thin wrapper over the object?

My attitude is: the thinnest wrapper is not the one that uses the least code.  The thinnest wrapper is the one that most nearly reproduces the affordances of the wrapped interface.  For example, I recently added a bunch of logic to `core.rtcpeerconnection` and `core.rtcdatachannel` to store, and then re-emit, early data channel events, to avoid losing them due to unavoidable asynchronicity.  I view this change similarly.

**Comment by iislucas** [comment]
This looks good to me. @trevj What do you mean by forcing people to use this? It seems to give strictly more/better information on a send call, which I like.

**Comment by trevj** [comment]
(Sorry, my last response didn't go out -- meant to send this days ago.)

@bemasc That previous change seems very important! This change seems *potentially* useful, although you're assuming users want to check the state before send is called -- that seems weird for a low-level piece of infrastructure, so a separate method may be more appropriate.

@iislucas This adds a `state` check to every send call; let's put it another way: would you write code that checked the connection state before every send? i don't think I would, given that `send` can raise exceptions, and that channels can fire a `close` event.

Anyway, I don't feel extremely strongly about this -- just pointing out what I think are some weirdnesses.

**Comment by iislucas** [comment]
Discussed in person some more with @bemasc and @trevj ; this LGTM

**Comment by soycode** [comment]
Checking on this - it looks reasonable to me, if we really want a situation where a call doesn't check for invalid state I'd be inclined to make that an optional bool argument ("force=true" or something). Is this still something we'd like to merge?

**Comment by soycode** [comment]
Checking again - is it still desired to merge this?

**Comment by bemasc** [comment]
I don't know what we want to do here.

**Comment by soycode** [comment]
Going to close this as stale for the time being - if there's interest/impetus to reopen that's fine by me.

**Pull request closed without merging**
