### PR TITLE
add npm shrinkwrap (freeze dependencies)

### LINKED ISSUE #311: npm shrinkwrap
I believe it's worth setting all the various freedom repos to use npm shrinkwrap, which basically generates a second npm manifest-ish .json that freezes the versions of all dependencies. Hopefully this helps stop our tests from changing their state underneath our feet.

### PR DESCRIPTION
**Pull request by soycode**
Fix #311 

Dependencies are fairly fresh, things that are held back are chosen on purpose (so that build/tests still work).

### CODE REVIEW

**Comment by soycode** [comment]
Assigning you all as FYI and consensus check - freedom.js has been pretty stable, and I think locking down the dependencies is a good bet. If anyone has objections please let me know by early next week - I intend to cut a release Wednesday morning at latest and merge this before doing so.

**Comment by willscott** [comment]
seems reasonable. :+1:

**Comment by soycode** [comment]
Hrm, that said it seems like "just add npm-shrinkwrap.json" breaks fresh installation in CI. Will update once I figure out the conflict.

**Comment by soycode** [comment]
Should be resolved - `fsevents` is an optional OSX-specific package that gets thrown in when you use npm on a Mac. Did `npm install --no-optional` instead of the regular `npm install` before shrinkwrapping, and now the result should be Linux-friendly.

**Comment by soycode** [comment]
Just to update/document - the plan is to merge this, cut a release, do similar bumping/freezing of the freedom flavors and cut those releases as well. I'll be working with @rajasagashe as he'll be taking over some of this (though his immediate focus will be node-wrtc related).

**Pull request merged**
